[package]
name = "async_net_experiment"
version = "0.6.7"
edition = "2024"

[dependencies]
futures = "0.3"
async-net = "1.7"
futures-timer = "3.0"
windows-sys = { version = "0.61", features = ["Win32_System_Console"] }
